export interface StaticEscort {
  id: string; name: string; age: number; city: string; area: string
  lat: number; lng: number; tier: string; rating: number; reviews_count: number
  bio: string; image: string; height: string; body_type: string
  ethnicity: string; hair_color: string
  price_hourly: number; price_overnight: number; price_video: number
  whatsapp: string; telegram: string
  available: boolean; verified: boolean; online: boolean
  languages: string[]; services: Array<{ name: string; available: boolean }>
  gallery: string[]
}

const U = (id: string, w = 600, h = 800) =>
  `https://images.unsplash.com/${id}?w=${w}&h=${h}&fit=crop&crop=face`

const PHOTOS = [
  'photo-1494790108377-be9c29b29330','photo-1534528741775-53994a69daeb',
  'photo-1531746020798-e6953c6e8e04','photo-1524504388940-b1c1722653e1',
  'photo-1529626455594-4ff0802cfb7e','photo-1488426862026-3ee34a7d66df',
  'photo-1508214751196-bcfd4ca60f91','photo-1544005313-94ddf0286df2',
  'photo-1517841905240-472988babdf9','photo-1573496359142-b8d87734a5a2',
  'photo-1552699611-b4cc0e76bc3f','photo-1564564321837-a57b7070ac4f',
  'photo-1531123897727-8f129e1688ce','photo-1536766820879-059fec98ec0a',
  'photo-1542037104857-ffbb0b9155fb','photo-1504257432389-52343af06ae3',
  'photo-1521146764736-56c929d59c83','photo-1533227268428-f9ed0900fb3b',
  'photo-1509967419530-da38b4704bc6','photo-1556157382-97eda2d62296',
]

const gallery = (main: string) => [
  U(main, 300, 400),
  ...PHOTOS.filter(p => p !== main).slice(0, 5).map(p => U(p, 300, 400)),
]

const VIP_SERVICES = [
  { name: 'Dinner Dates', available: true },{ name: 'Video Calls', available: true },
  { name: 'Overnight', available: true },   { name: 'Out-Call', available: true },
  { name: 'Travel Escort', available: true }, { name: 'Events & Functions', available: true },
  { name: 'Hotel Visits', available: true },
]
const STD_SERVICES = [
  { name: 'Dinner Dates', available: true },{ name: 'Video Calls', available: true },
  { name: 'Overnight', available: true },   { name: 'Out-Call', available: true },
  { name: 'Travel Escort', available: false }, { name: 'Events & Functions', available: false },
]

export const STATIC_ESCORTS: StaticEscort[] = [
  { id:'1',  name:'Amara K.',    age:24, city:'Nairobi',  area:'Nairobi CBD',      lat:-1.2921, lng:36.8219, tier:'elite',    rating:4.9, reviews_count:156, bio:'Elite escort based in Nairobi CBD. Sophisticated, discreet, and well-travelled.',                               image:U(PHOTOS[0]),  height:"5'6\"", body_type:'Slim/Athletic', ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:8000,  price_overnight:50000, price_video:3000, whatsapp:'254712345001', telegram:'amarak_wet3camp',    available:true,  verified:true,  online:true,  languages:['English','Swahili'],           services:VIP_SERVICES, gallery:gallery(PHOTOS[0])  },
  { id:'2',  name:'Zara M.',     age:26, city:'Nairobi',  area:'Westlands',         lat:-1.2679, lng:36.8082, tier:'vip',      rating:4.8, reviews_count:142, bio:'VIP escort in Westlands. Fluent in 3 languages, world-traveller, and passionate about providing a premium service.',  image:U(PHOTOS[1]),  height:"5'7\"", body_type:'Athletic',      ethnicity:'Kenyan',       hair_color:'Natural',     price_hourly:6500,  price_overnight:40000, price_video:2500, whatsapp:'254712345002', telegram:'zaram_wet3camp',     available:true,  verified:true,  online:true,  languages:['English','Swahili','French'],  services:VIP_SERVICES, gallery:gallery(PHOTOS[1])  },
  { id:'3',  name:'Luna K.',     age:23, city:'Nairobi',  area:'Karen',             lat:-1.3176, lng:36.7063, tier:'vip',      rating:4.7, reviews_count:128, bio:'Karen-based VIP escort. Known for my intelligence, elegance and impeccable style.',                               image:U(PHOTOS[2]),  height:"5'5\"", body_type:'Slim',          ethnicity:'Kenyan',       hair_color:'Dark Brown',  price_hourly:5000,  price_overnight:35000, price_video:2000, whatsapp:'254712345003', telegram:'lunak_wet3camp',     available:false, verified:true,  online:false, languages:['English','Swahili'],           services:VIP_SERVICES, gallery:gallery(PHOTOS[2])  },
  { id:'4',  name:'Sophia N.',   age:27, city:'Nairobi',  area:'Kilimani',          lat:-1.2903, lng:36.7855, tier:'premium',  rating:4.6, reviews_count:115, bio:'Premium Kilimani escort with a warm personality and stunning looks. Discretion guaranteed.',                         image:U(PHOTOS[3]),  height:"5'4\"", body_type:'Curvy',         ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:4000,  price_overnight:25000, price_video:1500, whatsapp:'254712345004', telegram:'sophian_wet3camp',   available:true,  verified:true,  online:true,  languages:['English','Swahili','Kikuyu'],  services:STD_SERVICES, gallery:gallery(PHOTOS[3])  },
  { id:'5',  name:'Priya S.',    age:25, city:'Nairobi',  area:'Lavington',         lat:-1.2820, lng:36.7726, tier:'premium',  rating:4.8, reviews_count:189, bio:'Half-Kenyan, half-Indian beauty residing in Lavington. Exotic, educated, and always well-presented.',               image:U(PHOTOS[4]),  height:"5'5\"", body_type:'Slim/Toned',    ethnicity:'Mixed',        hair_color:'Black',       price_hourly:5500,  price_overnight:38000, price_video:2200, whatsapp:'254712345005', telegram:'priyas_wet3camp',    available:true,  verified:true,  online:false, languages:['English','Hindi','Swahili'],   services:VIP_SERVICES, gallery:gallery(PHOTOS[4])  },
  { id:'6',  name:'Fatuma H.',   age:22, city:'Nairobi',  area:'Parklands',         lat:-1.2575, lng:36.8205, tier:'elite',    rating:4.9, reviews_count:203, bio:'Top-rated elite escort in Parklands. Coastal beauty who moved to Nairobi for a vibrant lifestyle.',                  image:U(PHOTOS[5]),  height:"5'6\"", body_type:'Slim',          ethnicity:'Swahili',      hair_color:'Black',       price_hourly:9000,  price_overnight:55000, price_video:3500, whatsapp:'254712345006', telegram:'fatumah_wet3camp',   available:true,  verified:true,  online:true,  languages:['English','Swahili','Arabic'],  services:VIP_SERVICES, gallery:gallery(PHOTOS[5])  },
  { id:'7',  name:'Grace W.',    age:28, city:'Nairobi',  area:'Upperhill',         lat:-1.3000, lng:36.8192, tier:'premium',  rating:4.5, reviews_count:97,  bio:"Professional escort based in Upperhill. Corporate-friendly, always punctual and impeccably dressed.",               image:U(PHOTOS[6]),  height:"5'7\"", body_type:'Athletic',      ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:4500,  price_overnight:28000, price_video:1800, whatsapp:'254712345007', telegram:'gracew_wet3camp',    available:true,  verified:true,  online:false, languages:['English','Swahili'],           services:STD_SERVICES, gallery:gallery(PHOTOS[6])  },
  { id:'8',  name:'Naomi J.',    age:24, city:'Nairobi',  area:'Gigiri',            lat:-1.2280, lng:36.8032, tier:'vip',      rating:4.7, reviews_count:134, bio:'Upscale escort in Gigiri, near the UN complex. Multilingual and experienced with international clients.',          image:U(PHOTOS[7]),  height:"5'8\"", body_type:'Slim/Tall',     ethnicity:'Kenyan',       hair_color:'Natural',     price_hourly:7000,  price_overnight:45000, price_video:3000, whatsapp:'254712345008', telegram:'naomij_wet3camp',    available:false, verified:true,  online:false, languages:['English','Swahili','German'],  services:VIP_SERVICES, gallery:gallery(PHOTOS[7])  },
  { id:'9',  name:'Aisha O.',    age:21, city:'Nairobi',  area:'South B',           lat:-1.3171, lng:36.8396, tier:'standard', rating:4.4, reviews_count:62,  bio:'Young, vibrant and fun-loving escort in South B. Fresh face on the platform but highly rated.',                    image:U(PHOTOS[8]),  height:"5'4\"", body_type:'Petite/Curvy',  ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:2500,  price_overnight:15000, price_video:1000, whatsapp:'254712345009', telegram:'aishao_wet3camp',    available:true,  verified:true,  online:true,  languages:['English','Swahili','Luo'],     services:STD_SERVICES, gallery:gallery(PHOTOS[8])  },
  { id:'10', name:'Cynthia M.',  age:29, city:'Nairobi',  area:'Runda',             lat:-1.2102, lng:36.8104, tier:'elite',    rating:4.9, reviews_count:178, bio:"Nairobi's finest escort — Runda based, world-class service. A decade of experience in high-end companionship.",     image:U(PHOTOS[9]),  height:"5'9\"", body_type:'Slim/Tall',     ethnicity:'Kenyan',       hair_color:'Relaxed/Dark',price_hourly:12000, price_overnight:75000, price_video:4500, whatsapp:'254712345010', telegram:'cyntham_wet3camp',   available:true,  verified:true,  online:true,  languages:['English','French','Swahili'],  services:VIP_SERVICES, gallery:gallery(PHOTOS[9])  },
  { id:'11', name:'Brenda A.',   age:23, city:'Nairobi',  area:'Langata',           lat:-1.3380, lng:36.7518, tier:'premium',  rating:4.6, reviews_count:88,  bio:'Langata beauty with a playful spirit. Always punctual and perfectly presented.',                                       image:U(PHOTOS[10]), height:"5'5\"", body_type:'Curvy',         ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:3500,  price_overnight:22000, price_video:1500, whatsapp:'254712345011', telegram:'brendaa_wet3camp',   available:true,  verified:false, online:true,  languages:['English','Swahili'],           services:STD_SERVICES, gallery:gallery(PHOTOS[10]) },
  { id:'12', name:'Diana V.',    age:26, city:'Nairobi',  area:'Eastleigh',         lat:-1.2726, lng:36.8478, tier:'standard', rating:4.3, reviews_count:54,  bio:'Vibrant Eastleigh escort. Somali heritage with a warm, welcoming personality.',                                    image:U(PHOTOS[11]), height:"5'6\"", body_type:'Slim',          ethnicity:'Somali-Kenyan',hair_color:'Black',       price_hourly:2000,  price_overnight:12000, price_video:800,  whatsapp:'254712345012', telegram:'dianav_wet3camp',    available:true,  verified:true,  online:false, languages:['English','Swahili','Somali'],  services:STD_SERVICES, gallery:gallery(PHOTOS[11]) },
  { id:'13', name:'Sharon K.',   age:25, city:'Nairobi',  area:'Embakasi',          lat:-1.3211, lng:36.9009, tier:'standard', rating:4.2, reviews_count:47,  bio:'Embakasi escort offering great value. Happy to travel within Nairobi at no extra charge.',                          image:U(PHOTOS[0]),  height:"5'3\"", body_type:'Average',       ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:1800,  price_overnight:10000, price_video:700,  whatsapp:'254712345013', telegram:'sharonk_wet3camp',   available:false, verified:false, online:false, languages:['English','Swahili'],           services:STD_SERVICES, gallery:gallery(PHOTOS[0])  },
  { id:'14', name:'Kezia N.',    age:22, city:'Nairobi',  area:'Ngong Road',        lat:-1.3028, lng:36.7677, tier:'premium',  rating:4.7, reviews_count:103, bio:'Slim and elegant escort along Ngong Road. University-educated, articulate and refined.',                             image:U(PHOTOS[1]),  height:"5'6\"", body_type:'Slim/Toned',    ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:3800,  price_overnight:24000, price_video:1600, whatsapp:'254712345014', telegram:'kezian_wet3camp',    available:true,  verified:true,  online:true,  languages:['English','Swahili'],           services:STD_SERVICES, gallery:gallery(PHOTOS[1])  },
  { id:'15', name:'Mercy T.',    age:27, city:'Nairobi',  area:'Thika Road',        lat:-1.2253, lng:36.8944, tier:'vip',      rating:4.6, reviews_count:121, bio:'Thika Road VIP escort with a bubbly personality. Available for bookings citywide.',                                  image:U(PHOTOS[2]),  height:"5'5\"", body_type:'Curvy',         ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:5000,  price_overnight:30000, price_video:2000, whatsapp:'254712345015', telegram:'mercyt_wet3camp',    available:true,  verified:true,  online:false, languages:['English','Swahili','Kikuyu'],  services:VIP_SERVICES, gallery:gallery(PHOTOS[2])  },
  { id:'16', name:'Wanjiku G.', age:30, city:'Mombasa', area:'Nyali',              lat:-4.0165, lng:39.7057, tier:'elite',    rating:4.9, reviews_count:231, bio:"The queen of the Kenyan coast — Nyali's finest. My clientele includes diplomats and executives.",                       image:U(PHOTOS[3]),  height:"5'8\"", body_type:'Slim/Curvy',    ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:10000, price_overnight:60000, price_video:4000, whatsapp:'254712345016', telegram:'wanjikug_wet3camp',  available:true,  verified:true,  online:true,  languages:['English','Swahili','Portuguese'],services:VIP_SERVICES,gallery:gallery(PHOTOS[3]) },
  { id:'17', name:'Akinyi B.',   age:23, city:'Mombasa', area:'Bamburi',            lat:-3.9835, lng:39.7287, tier:'premium',  rating:4.5, reviews_count:76,  bio:"Beach babe from Bamburi, Mombasa. Sun-kissed, carefree and unforgettably sensual.",                                    image:U(PHOTOS[4]),  height:"5'5\"", body_type:'Athletic',      ethnicity:'Luo-Kenyan',   hair_color:'Natural',     price_hourly:4000,  price_overnight:25000, price_video:1500, whatsapp:'254712345017', telegram:'akinyib_wet3camp',   available:true,  verified:true,  online:true,  languages:['English','Swahili','Luo'],     services:STD_SERVICES, gallery:gallery(PHOTOS[4])  },
  { id:'18', name:'Amina S.',    age:25, city:'Mombasa', area:'Mombasa CBD',        lat:-4.0435, lng:39.6682, tier:'vip',      rating:4.7, reviews_count:145, bio:'Mombasa CBD beauty with coastal charm and big-city sophistication. Experienced with international clientele.',         image:U(PHOTOS[5]),  height:"5'6\"", body_type:'Slim',          ethnicity:'Swahili',      hair_color:'Black',       price_hourly:5500,  price_overnight:35000, price_video:2200, whatsapp:'254712345018', telegram:'aminas_wet3camp',    available:false, verified:true,  online:false, languages:['English','Swahili','Arabic'],  services:VIP_SERVICES, gallery:gallery(PHOTOS[5])  },
  { id:'19', name:'Stella R.',   age:24, city:'Mombasa', area:'Diani',              lat:-4.2792, lng:39.5915, tier:'vip',      rating:4.8, reviews_count:163, bio:'Diani beach escort — your ultimate coastal fantasy.',                                                                   image:U(PHOTOS[6]),  height:"5'7\"", body_type:'Toned',         ethnicity:'Kenyan',       hair_color:'Dark Brown',  price_hourly:6000,  price_overnight:40000, price_video:2500, whatsapp:'254712345019', telegram:'stellar_wet3camp',   available:true,  verified:true,  online:true,  languages:['English','Swahili','Italian'], services:VIP_SERVICES, gallery:gallery(PHOTOS[6])  },
  { id:'20', name:'Janet L.',    age:29, city:'Mombasa', area:'Mtwapa',             lat:-3.9405, lng:39.7345, tier:'premium',  rating:4.4, reviews_count:83,  bio:'Mtwapa escort offering premium coastal experiences. Mature, confident and extremely accommodating.',                    image:U(PHOTOS[7]),  height:"5'4\"", body_type:'Curvy',         ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:3500,  price_overnight:22000, price_video:1400, whatsapp:'254712345020', telegram:'janetl_wet3camp',    available:true,  verified:false, online:false, languages:['English','Swahili'],           services:STD_SERVICES, gallery:gallery(PHOTOS[7])  },
  { id:'21', name:'Adhiambo P.', age:22, city:'Kisumu',  area:'Milimani',           lat:-0.0917, lng:34.7680, tier:'premium',  rating:4.6, reviews_count:69,  bio:"Kisumu's premier escort based in upscale Milimani. Luo beauty with an outgoing personality.",                      image:U(PHOTOS[8]),  height:"5'5\"", body_type:'Petite/Slim',   ethnicity:'Luo',          hair_color:'Black',       price_hourly:3000,  price_overnight:20000, price_video:1200, whatsapp:'254712345021', telegram:'adhiambop_wet3camp', available:true,  verified:true,  online:true,  languages:['English','Swahili','Luo'],     services:STD_SERVICES, gallery:gallery(PHOTOS[8])  },
  { id:'22', name:'Evalyne O.',  age:26, city:'Kisumu',  area:'Kisumu CBD',         lat:-0.1022, lng:34.7617, tier:'standard', rating:4.3, reviews_count:44,  bio:'Kisumu lakeside beauty with a genuine, approachable personality.',                                                       image:U(PHOTOS[9]),  height:"5'4\"", body_type:'Average',       ethnicity:'Luo',          hair_color:'Black',       price_hourly:2000,  price_overnight:13000, price_video:800,  whatsapp:'254712345022', telegram:'evalyneo_wet3camp',  available:true,  verified:false, online:false, languages:['English','Swahili','Luo'],     services:STD_SERVICES, gallery:gallery(PHOTOS[9])  },
  { id:'23', name:'Pauline R.',  age:28, city:'Nakuru',  area:'Nakuru CBD',         lat:-0.3031, lng:36.0800, tier:'premium',  rating:4.5, reviews_count:57,  bio:"Rift Valley's finest escort based in Nakuru.",                                                                        image:U(PHOTOS[10]), height:"5'5\"", body_type:'Slim',          ethnicity:'Kenyan',       hair_color:'Black',       price_hourly:3200,  price_overnight:20000, price_video:1300, whatsapp:'254712345023', telegram:'pauliner_wet3camp',  available:false, verified:true,  online:false, languages:['English','Swahili','Kikuyu'],  services:STD_SERVICES, gallery:gallery(PHOTOS[10]) },
  { id:'24', name:'Sandra C.',   age:25, city:'Nakuru',  area:'Milimani Nakuru',    lat:-0.2882, lng:36.0610, tier:'vip',      rating:4.7, reviews_count:92,  bio:"VIP escort in Nakuru's prestigious Milimani area. City girl with small-town warmth.",                                  image:U(PHOTOS[11]), height:"5'6\"", body_type:'Athletic',      ethnicity:'Kenyan',       hair_color:'Dark Brown',  price_hourly:4500,  price_overnight:28000, price_video:1800, whatsapp:'254712345024', telegram:'sandrac_wet3camp',   available:true,  verified:true,  online:true,  languages:['English','Swahili'],           services:VIP_SERVICES, gallery:gallery(PHOTOS[11]) },
  { id:'25', name:'Faith C.',    age:23, city:'Eldoret', area:'Eldoret CBD',        lat:0.5143,  lng:35.2698, tier:'standard', rating:4.4, reviews_count:38,  bio:"North Rift's charming escort in Eldoret. Kalenjin beauty with an infectious laugh.",                                    image:U(PHOTOS[0]),  height:"5'6\"", body_type:'Slim/Athletic', ethnicity:'Kalenjin',     hair_color:'Black',       price_hourly:2200,  price_overnight:14000, price_video:900,  whatsapp:'254712345025', telegram:'faithc_wet3camp',    available:true,  verified:false, online:false, languages:['English','Swahili','Kalenjin'],services:STD_SERVICES, gallery:gallery(PHOTOS[0])  },
]
