import { Router, type IRouter } from "express";
import healthRouter        from "./health.js";
import escortsRouter       from "./escorts.js";
import authRouter          from "./auth.js";
import oauthRouter         from "./oauth.js";
import messagesRouter      from "./messages.js";
import bookingsRouter      from "./bookings.js";
import favoritesRouter     from "./favorites.js";
import reviewsRouter       from "./reviews.js";
import adminRouter         from "./admin.js";
import profileRouter       from "./profile.js";
import sseRouter           from "./sse.js";
import sitemapRouter       from "./sitemap.js";
import roomsRouter         from "./rooms.js";
import aiRouter            from "./ai.js";
import uploadRouter        from "./upload.js";
import notificationsRouter from "./notifications.js";
import webrtcRouter        from "./webrtc.js";
import claimsRouter        from "./claims.js";
import contentRouter       from "./content.js";
import liveRouter          from "./live.js";
import paymentsRouter      from "./payments.js";
import referralRouter      from "./referral.js";
import imageProxyRouter    from "./image-proxy.js";
import blogRouter          from "./blog.js";

const router: IRouter = Router();

router.use(imageProxyRouter);
router.use(liveRouter);
router.use(paymentsRouter);
router.use(webrtcRouter);
router.use(healthRouter);
router.use(escortsRouter);
router.use(authRouter);
router.use(oauthRouter);
router.use(messagesRouter);
router.use(bookingsRouter);
router.use(favoritesRouter);
router.use(reviewsRouter);
router.use(adminRouter);
router.use(profileRouter);
router.use(sseRouter);
router.use(sitemapRouter);
router.use(roomsRouter);
router.use(aiRouter);
router.use(uploadRouter);
router.use(notificationsRouter);
router.use(claimsRouter);
router.use(contentRouter);
router.use(referralRouter);
router.use(blogRouter);

export default router;
